import json


def build_moderation_request(path="/moderation/resume"):
    payload = {
        "replicationHeartbeat": 1725142078866,
        "id": 122093007,
        "userId": 60562463,
        "hhid": 51291704,
        "status": "new",
        "moderationTime": None,
        "creationTime": 1566388500009,
        "lastChangeTime": 1725139113637,
        "lastEditTime": 1725139061853,
        "markService": False,
        "markServiceExpireTime": None,
        "renewalService": False,
        "renewalServiceExpireTime": None,
        "secretWord": "JgfdsD",
        "source": "short",
        "validationSchema": None,
        "salary": {"amount": 3000, "currency": "BYR"},
        "predictedSalary": None,
        "lastChangeTimeDetails": {"year": "2024", "month": "9", "day": "1", "hour": "00", "minute": "18"},
        "profArea": 15,
        "specialization": ["750"],
        "specializationTree": [
            {
                "id": 15,
                "name": "professional_area.15",
                "title": None,
                "translit": "nachalo-karery-studenty",
                "specialization": [
                    {"id": 750, "name": "specialization.750", "translit": "Drugoe", "title": None, "isLabour": False}
                ],
            }
        ],
        "professionalRole": ["40"],
        "birthday": "1998-01-14",
        "metro": None,
        "metroStation": None,
        "readyForTemporaryJob": None,
        "relocationArea": [],
        "relocationAreaPath": [],
        "relocationDistrict": [],
        "residenceDistrict": [],
        "relocationAreaExtended": None,
        "citizenship": [16],
        "primaryEducation": [
            {
                "id": 357898997,
                "name": "ПГПТК",
                "year": 2016,
                "organization": None,
                "result": None,
                "universityId": None,
                "specialtyId": None,
                "facultyId": None,
            }
        ],
        "certificate": [],
        "language": [{"id": 34, "degree": "l1"}],
        "phone": [
            {
                "type": "cell",
                "country": "375",
                "city": "33",
                "number": "3613316",
                "formatted": "+375 (33) 321-53-16",
                "raw": "375333215316",
                "verified": True,
                "needVerification": False,
                "comment": None,
            }
        ],
        "photo": None,
        "photoUrls": None,
        "moderationNotes": [],
        "keySkills": ["Работоспособность"],
        "keySkillsConfirmedByProviders": {"skillIdsToProviders": {}, "promotedProviders": [], "otherProviders": []},
        "lang": "ru",
        "title": "Начинающий специалист",
        "firstName": "Ирина",
        "middleName": None,
        "lastName": "Вукуц",
        "gender": "female",
        "age": 26,
        "email": "llkdw.to@tut.ru",
        "area": 1002,
        "areaPath": ".16.1002.",
        "relocation": "no_relocation",
        "workSchedule": ["full_day"],
        "employment": ["full"],
        "educationLevel": "special_secondary",
        "preferredContact": "email",
        "totalExperience": 0,
        "experienceStart": 1725142978878,
        "workExperienceCalculationTime": None,
        "workExperience": "no_work_experience",
        "accessType": "clients",
        "hasVehicle": None,
        "driverLicenseTypes": [],
        "hiddenFields": [],
        "autoHideTime": "month_12",
        "hash": None,
        "permission": None,
        "additionalEducation": [],
        "advancedKeySkills": [
            {"name": "Работоспособность", "general": True, "id": 2575, "isConfirmedByExperience": None}
        ],
        "attestationEducation": [],
        "businessTripReadiness": "never",
        "elementaryEducation": [],
        "experience": [],
        "lastExperience": None,
        "moderationFlags": [],
        "moderFullName": {"firstName": "Алексей", "middleName": None, "lastName": "Дубунов"},
        "personalSite": [],
        "portfolio": [],
        "portfolioUrls": [],
        "recommendation": [],
        "skills": None,
        "travelTime": "any",
        "workTicket": [16],
    }

    return {
        "path": path,
        "content_type": "application/json",
        "method": "POST",
        "data": json.dumps(payload),
    }
